apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-service
spec:
  selector:
    app: springbootactuator
  ports:
    - name: web
      port: 9000   
      targetPort: 8080
  type: NodePort